spring:
  application:
    name: Gateway  # Nom du service Gateway
  cloud:
    consul:
      host: localhost     # Hôte où Consul est en cours d'exécution
      port: 8500          # Port par défaut de Consul
      discovery:
        enabled: true     # Activer la découverte de services via Consul

server:
  port: 8888  # Port pour le projet Gateway
